const LOGIN ='LOGIN'
const CANCEL_LOGIN='CANCEL_LOGIN'
const SET_USER_NAME='SET_USER_NAME'
const SET_TOKEN ='SET_TOKEN'
const REFETCH_MY_TEMPLATE_DATAS='REFETCH_MY_TEMPLATE_DATAS'

export {LOGIN,CANCEL_LOGIN,SET_USER_NAME,SET_TOKEN,REFETCH_MY_TEMPLATE_DATAS}